/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */

node ('ubuntu1804-docker-4c-4g') {

    def lib = library("jenkins-library").org.zowe.jenkins_shared_library

    def pipeline = lib.pipelines.docker.DockerPipeline.new(this)

    pipeline.admins.add("markackert", "jackjia.ibm")

    pipeline.setup(
        github: [
                email                      : lib.Constants.DEFAULT_GITHUB_ROBOT_EMAIL,
                usernamePasswordCredential : lib.Constants.DEFAULT_LFJ_GITHUB_ROBOT_CREDENTIAL,
        ],
        packageName: 'org.zowe.jenkins-library.zowe-jenkins-license-scan',
        githubTagPrefix: 'zowe-license-scanning',
        docker: [
            url                        : lib.Constants.DEFAULT_LFJ_DOCKER_REGISTRY_URL,
            usernamePasswordCredential : lib.Constants.DEFAULT_LFJ_DOCKER_REGISTRY_CREDENTIAL,
            // prefix should be synced with credential
            image                      : "zowehub/zowe-license-scanning".toString(),
            dockerFile                 : "dockerfiles/license-scanning/Dockerfile"
        ],
        disableArtifactory: true,
        disablePax:  true
    )

    pipeline.createStage(name: 'Prepare Dockerfile', stage: {
        sh "cd dockerfiles/license-scanning && ./build.sh"
    });

    // default build stage, dockerFile is {@code "Dockerfile"}
    pipeline.build()

    // default publish stage, image is "${lib.Constants.DEFAULT_DOCKER_IMAGE_PREFIX}/zowe-jenkins-base"
    pipeline.publish()

    // we have release stage
    pipeline.release()

    pipeline.end()
}